const base = "/assets/figma";

export const figmaAssets = {
  manifest: `${base}/manifest.json`,
  hero: {
    homeBackground: `${base}/home-hero-new/consultant-background.png`,
    homeOverlay: `${base}/home-hero-new/teal-overlay.svg`,
    homeWave: `${base}/home-hero-new/bottom-wave.svg`,
    homeBookStack: `${base}/library/hero/home-03.webp`,
    servicesBackground: `${base}/lp-hero-new/background-wide.png`,
    pageWave: `${base}/shared/page-wave.svg`,
  },
  cta: {
    publishingSteps: `${base}/library/cta/publishing-steps-01.webp`,
    publishingServices: `${base}/shared/publishing-services-collage-120-2642.png`,
    publishingServicesOutline: `${base}/shared/publishing-services-outline-120-2643.svg`,
    booksComposite: `${base}/shared/cta-books-composite-primary.png`,
    booksCompositeBackground: `${base}/shared/cta-books-composite-secondary.png`,
    turningIdeasBooks: `${base}/library/testimonials/asset-01.webp`,
  },
  footer: {
    divider: `${base}/shared/footer-divider.svg`,
    aboutDivider: `${base}/shared/footer-divider-about.svg`,
    servicesDivider: `${base}/shared/footer-divider-white.svg`,
  },
  brand: {
    partners: {
      authorLab: `${base}/partners/authorlab.png`,
      scribd: `${base}/partners/scribd.png`,
      ingram: `${base}/partners/ingram.png`,
      bookPrinting: `${base}/partners/bookprinting.png`,
      ingramSpark: `${base}/partners/ingramspark.png`,
      kobo: `${base}/partners/kobo.png`,
      lulu: `${base}/partners/lulu.png`,
    },
  },
  services: {
    ghostwriting: `${base}/library/brand-services/asset-12.webp`,
    sectionWave: `${base}/shared/services-section-wave.svg`,
    homeMedia: [
      `${base}/library/services/home-service-01.webp`,
      `${base}/library/services/home-service-02.webp`,
      `${base}/library/services/home-service-03.webp`,
      `${base}/library/services/home-service-04.webp`,
    ],
    timelineMedia: {
      ghostwriting: `${base}/library/brand-services/asset-12.webp`,
      editing: `${base}/library/services/home-service-01.webp`,
      design: `${base}/library/brand-services/asset-19.webp`,
      publishing: `${base}/library/services/home-service-04.webp`,
      audiobook: `${base}/library/services/home-service-03.webp`,
      marketing: `${base}/library/brand-services/asset-17.webp`,
    },
    cards: [
      `${base}/library/services/service-card-01.webp`,
      `${base}/library/services/service-card-02.webp`,
      `${base}/library/services/service-card-03.webp`,
      `${base}/library/services/service-card-04.webp`,
    ],
  },
  servicesPage: {
    introCollage: `${base}/library/services-page/intro-collage.png`,
    heroOverlay: `${base}/lp-hero-new/teal-overlay.svg`,
    heroWave: `${base}/lp-hero-new/bottom-wave.svg`,
    workWave: `${base}/shared/services-page-work-wave.svg`,
  },
  aboutPage: {
    heroBackground: `${base}/about/about-hero-bg.jpg`,
    heroWave: `${base}/about/about-hero-wave.svg`,
    heroArtwork: {
      left: `${base}/about/hero-art/left-device-transparent.png`,
      right: `${base}/about/hero-art/right-books-device-transparent.png`,
    },
    flyingBooks: `${base}/about/flying-books.png`,
    benefitIcons: {
      author: `${base}/about/icon-author.svg`,
      experts: `${base}/about/icon-experts.svg`,
      rights: `${base}/about/icon-rights.svg`,
      pricing: `${base}/about/icon-pricing.svg`,
      support: `${base}/about/icon-support.svg`,
      record: `${base}/about/icon-record.svg`,
    },
    services: {
      ghostwriting: `${base}/about/service-ghostwriting.png`,
      editing: `${base}/about/service-editing.png`,
      design: `${base}/about/service-design.png`,
      publishing: `${base}/about/service-publishing.png`,
      audiobook: `${base}/about/service-audiobook.png`,
      marketing: `${base}/about/service-marketing.png`,
    },
    ctaBooks: `${base}/about/cta-books.png`,
    ctaMask: `${base}/about/cta-mask.svg`,
  },
  ghostwritingPage: {
    heroBackground: `${base}/ghostwriting/hero-background.jpg`,
    heroWave: `${base}/ghostwriting/hero-wave.svg`,
    heroArtwork: {
      left: `${base}/ghostwriting/hero-art/left-books-transparent.png`,
      right: `${base}/ghostwriting/hero-art/right-device-transparent.png`,
    },
    benefitIcons: {
      dedicatedWriter: `${base}/ghostwriting/icon-dedicated-writer.svg`,
      checkIns: `${base}/ghostwriting/icon-check-ins.svg`,
      confidentiality: `${base}/ghostwriting/icon-confidentiality.svg`,
      ownership: `${base}/ghostwriting/icon-ownership.svg`,
      revisions: `${base}/ghostwriting/icon-revisions.svg`,
    },
    ctaBooks: `${base}/ghostwriting/cta-books.png`,
    ctaMask: `${base}/ghostwriting/cta-mask.svg`,
    processBooks: `${base}/ghostwriting/process-books.png`,
    processWave: `${base}/ghostwriting/process-wave.svg`,
  },
  packagesPage: {
    heroBackground: `${base}/packages/hero-background.jpg`,
    heroWave: `${base}/packages/hero-wave.svg`,
    heroArtwork: {
      left: `${base}/packages/hero-art/left-book.png`,
      right: `${base}/packages/hero-art/right-publishing.png`,
    },
  },
  portfolio: {
    rowOne: [
      `${base}/library/books/portfolio-21.webp`,
      `${base}/library/books/portfolio-14.webp`,
      `${base}/library/books/portfolio-11.webp`,
      `${base}/library/books/portfolio-22.webp`,
      `${base}/library/books/portfolio-18.webp`,
      `${base}/library/books/portfolio-16.webp`,
    ],
    rowTwo: [
      `${base}/library/books/portfolio-17.webp`,
      `${base}/library/books/portfolio-13.webp`,
      `${base}/library/books/portfolio-05.webp`,
      `${base}/library/books/portfolio-24.webp`,
      `${base}/library/books/portfolio-04.webp`,
      `${base}/library/books/portfolio-26.webp`,
      `${base}/library/books/portfolio-07.webp`,
    ],
  },
  process: {
    floatingBooks: `${base}/library/process/asset-03.webp`,
    shelf: `${base}/library/process/shelf-single.png`,
    launchBooks: [
      `${base}/library/process/asset-07.webp`,
      `${base}/library/process/asset-04.webp`,
      `${base}/library/process/asset-13.webp`,
      `${base}/library/process/asset-14.webp`,
      `${base}/library/process/asset-13.webp`,
    ],
  },
  testimonials: {
    background: `${base}/library/testimonials/asset-02.webp`,
  },
  icons: {
    quality: `${base}/shared/feature-quality-120-2502.svg`,
    transparency: `${base}/shared/feature-transparency-120-2509.svg`,
    vision: `${base}/shared/feature-vision-120-2516.svg`,
    experience: `${base}/shared/feature-experience-120-2521.svg`,
    check: `${base}/shared/check-circle.svg`,
    arrowUp: `${base}/shared/arrow-up.svg`,
    chevronDown: `${base}/shared/chevron-down.svg`,
    phone: `${base}/shared/phone.svg`,
    mail: `${base}/shared/mail.svg`,
    location: `${base}/shared/location.svg`,
  },
  payments: {
    visa: `${base}/shared/payment-visa.svg`,
    mastercard: `${base}/shared/payment-mastercard.svg`,
    discover: `${base}/shared/payment-discover.svg`,
    americanExpress: `${base}/shared/payment-amex.svg`,
  },
} as const;

export type FigmaAssets = typeof figmaAssets;
